### ISSUE TITLE
osu! Standard Stats not updating on my profile

### ISSUE THREAD

**Issue by Fiabilandia** [Adrriii/osudaily#12]
So i made a longer break from playing Standard Mode, so therefore there were no plays for a longer period of time (07/17/2023 - 10/04/2023) and no stats to be updated on my osu!daily profile. Only the stats for Mania were updating because i was actively playing in that mode.

I started picking up STD again but the graphs and numbers for the last two days do not show up on my profile. The Mania stats on the other hand were updating properly.

So my question is,
Does it take more time for the website to recognize new plays in that specific game mode or is it generally not updating the stats any time soon?

![image](https://github.com/Adrriii/osudaily/assets/147161128/83359966-9836-4f3f-abba-215748dc1296)

![image](https://github.com/Adrriii/osudaily/assets/147161128/23217004-5449-45f5-86d4-067ce1f0121e)

**Comment by Adrriii** [comment]
After becoming inactive/restricted/banned, osu! will stop providing data on its API.
After a few unsuccessful tries, in order to avoid making unnecessary requests, I automatically stop requesting each day for the user+mode, and start requesting only each week.

Supposedly, when a request is successful (in the each week batch), the condition reset and starts to request each day again. But this doesn't work sometimes. It's been broken for a really long time and I can't fix it easily.

**Comment by Fiabilandia** [comment]
Okay, i understood well!
Thank you!
