### ISSUE TITLE
3 Gamemodes no longer updating anymore

### ISSUE THREAD

**Issue by Fiabilandia** [Adrriii/osudaily#14]
As a follow-up to Issue #12 ["osu! Standard Stats not updating on my profile"] I've experienced that the modes (STD, Taiko, CTB) which I play regularly are not updating in any way since October 28th. No data gets updated on my profile except the ones for Mania Mode (Daily updated data). 

I know that the issue preexists already and that it gets worked on but i wanted to share this new development regarding the issue submitted in the past so that the developer can keep a better eye on troubleshooting :- )

**Comment by Adrriii** [comment]
Yes this is still related, there is a rate-limit automatically applied when users have been inactive/restricted to check once per week instead of daily (saving tens of thousands of requests)
Howere there is a very ancient bug that prevents the user from being tracked daily afterwards, and I haven't managed to fix it yet.

**Comment by richardwdoty** [comment]
Just following up on this. Is there any workaround? My stats are now only updated weekly rather than daily

**Comment by Adrriii** [comment]
Should be fixed. Please follow up only if you still experience this
